### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Bipbip2109** [Null-MC/Arc-Shader#2]
Specs:
   CPU: Intel i3-9100F
   GPU: NVIDIA GeForce RTX 2060 SUPER
   RAM: 12G/16G allocated (no bottleneck)
   OS: Win 11 Insider
   JAVA: OpenJDK JRE 17.0.3 64bit

MC Version: Fabric 14.9 1.19.2
Shader version: 0.6
Sodium 0.4.4 + Iris 1.3.0 or previous

Simply doesn't work (fallback)

Logs:
Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: net.minecraft.class_2973: Invalid shaders/core/clouds.json: Couldn't compile fragment program (<iris shaderpack shaders>, clouds) : 0(895) : error C1503: undefined variable "alphaTestRef"
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:352)
	at net.coderbot.iris.pipeline.newshader.ShaderMap.<init>(ShaderMap.java:21)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:339)
	at net.coderbot.iris.Iris.createPipeline(Iris.java:659)
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34)
	at net.coderbot.iris.Iris.reload(Iris.java:601)
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28)
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:491)
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$2(ShaderPackScreen.java:218)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:172)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_2973: Invalid shaders/core/clouds.json: Couldn't compile fragment program (<iris shaderpack shaders>, clouds) : 0(895) : error C1503: undefined variable "alphaTestRef"
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:200)
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.<init>(ExtendedShader.java:52)
	at net.coderbot.iris.pipeline.newshader.NewShaderTests.create(NewShaderTests.java:130)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:431)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:420)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:348)
	... 31 more
Caused by: java.io.IOException: Couldn't compile fragment program (<iris shaderpack shaders>, clouds) : 0(895) : error C1503: undefined variable "alphaTestRef"
	at net.minecraft.class_281.method_34416(class_281.java:69)
	at net.minecraft.class_281.method_1283(class_281.java:51)
	at net.minecraft.class_5944.method_34579(class_5944.java:238)
	at net.minecraft.class_5944.<init>(class_5944.java:183)
	... 36 more

**Comment by null511** [comment]
looks like you're using Iris, did you turn off the "Optifine?" option in the shader settings?

**Comment by Bipbip2109** [comment]
yeah

**Comment by Bipbip2109** [comment]
Global Illumination too
