### ISSUE TITLE
Crashes on Iris for me

### ISSUE THREAD

**Issue by rapus95** [Null-MC/Arc-Shader#4]
It started with destroying pipeline because I enabled Iris and hit Apply. Btw isn't there any way to autodetect iris/optifine?
```
[19:25:45] [Render thread/INFO]: Destroying pipeline OVERWORLD
[19:25:45] [Render thread/WARN]: Unable to resolve shader pack option menu element "WATER_POROSITY_DARKEN" defined in shaders.properties
[19:25:45] [Render thread/INFO]: Profile: ULTRA (+1 option changed by user)
[19:25:46] [Render thread/INFO]: Using shaderpack: Arc_v0.15.2.zip
[19:25:46] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[19:25:46] [Render thread/INFO]: Starting custom uniform resolving
[19:25:46] [Render thread/WARN]: Shader compilation log for deferred4.fsh: ERROR: 0:267: 'cascadeViewMin' : undeclared identifier 
ERROR: 0:267: 'cascadeViewMin' :  left of '[' is not of type array, matrix, or vector  
ERROR: 0:267: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
[19:25:46] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
net.coderbot.iris.gl.shader.ShaderCompileException: deferred4.fsh: ERROR: 0:267: 'cascadeViewMin' : undeclared identifier 
ERROR: 0:267: 'cascadeViewMin' :  left of '[' is not of type array, matrix, or vector  
ERROR: 0:267: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:46) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:25) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:99) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:52) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:337) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:116) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:256) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:664) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.Iris.reload(Iris.java:606) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:557) ~[transformed-mod-iris.i0:0/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:242) ~[transformed-mod-iris.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:172) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[transformed-mod-minecraft.i0:0/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:196) ~[transformed-mod-iris.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[transformed-mod-minecraft.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1225) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.5.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.5.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[19:25:46] [Render thread/INFO]: Stopping worker threads
[19:25:46] [Render thread/INFO]: Started 6 worker threads
```

**Comment by null511** [comment]
There isn't a reliable way to detect Iris yet; they just added a flag for it, but I can't reliably use it until the Iris 1.6 release stabilizes.

As for the errors, that looks like something I may have messed up so I'll look into it. What version of Iris are you on though? The colored lights & cascaded shadow features only work on the latest Iris 1.6 beta

**Comment by rapus95** [comment]
![image](https://user-images.githubusercontent.com/5960902/226739734-3c3860c0-e402-47b8-8734-373dd902a28b.png)

So yes, I guess I messed up compatibility x) My iris is too old, isn't it?

**Comment by null511** [comment]
Right, you need 1.6 for the advanced features. You can grab the latest Iris 1.6 beta 3 from the Iris disord:
https://discord.com/channels/774352792659820594/1088486917307383848
